services:
  app:
    build: . 
    container_name: python-dev-env
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    volumes: 
      - .:/code
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root